### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by JeffJag-ETH** [Millyarde/Pomfy#2]
![image](https://github.com/Millyarde/Pomfy/assets/119813682/1048e399-d863-4309-9f52-4fb52595ac3c)
can not get it connected.

I installed uxp devmode and successfully loaded the plugin in the UXP app, but I keep getting this error:

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by Millyarde** [comment]
Hi @JeffJag-ETH, the plugin is still being developed. I'll hopefully have an alpha released here in a week or two. I'll post a release on the [Release page](https://github.com/Millyarde/Pomfy/releases) with install instructions when it is out and fully working!

Thank you for your interest!
